# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-06 13:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buku', '0001_initial'),
        ('mahasiswa', '0002_auto_20170906_1344'),
    ]

    operations = [
        migrations.CreateModel(
            name='Peminjaman',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tgl_pinjam', models.DateField()),
                ('bts_pinjam', models.DateField()),
                ('buku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bukus', to='buku.Buku')),
                ('mahasiswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mahasiswas', to='mahasiswa.Mahasiswa')),
            ],
            options={
                'ordering': ['-id'],
                'db_table': 'peminjam',
            },
        ),
    ]
