# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-06 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mahasiswa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nim', models.CharField(max_length=10)),
                ('nama', models.TextField(max_length=100)),
                ('prodi', models.TextField(max_length=100)),
                ('semester', models.IntegerField(max_length=5)),
            ],
            options={
                'ordering': ['-id'],
                'db_table': 'mahasiswa',
            },
        ),
    ]
