# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-06 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahasiswa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mahasiswa',
            name='semester',
            field=models.IntegerField(),
        ),
    ]
